version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.3.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data

  kibana:
    image: kibana:7.3.1
    ports:
      - "5601:5601"
    volumes:
      - ./config/kibana/kibana.yml:/usr/share/kibana/kibana.yml

volumes:
  esdata:
    driver: local
